<a href="https://colab.research.google.com/github/EzeChiappero/freecodecamp-intro-to-numpy/blob/master/2.%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [1]:
import sys
import numpy as np

In [59]:
2** 38 / 1000000000


274.877906944

## Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [62]:
a = np.array([1, 2, 3, 4,5,6,7])

In [70]:
b = np.array([0, .5, 1, 1.5, 2,2.5])

In [5]:
a[0], a[1]

(1, 2)

In [65]:
a[0:]

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
a[1:3]

array([2, 3])

In [63]:
a[1:-1]

array([2, 3, 4, 5, 6])

In [67]:
a[::2]

array([1, 3, 5, 7])

In [71]:
b

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [72]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.5)

In [73]:
b[[0, 2, -1]]

array([0. , 1. , 2.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [16]:
a

array([1, 2, 3, 4])

In [26]:
a.dtype

dtype('int64')

In [27]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [29]:
b.dtype

dtype('float64')

In [74]:
np.array([1, 2, 3, 4,5,6,7], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4., 5., 6., 7.])

In [75]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [76]:
c = np.array(['a', 'b', 'c'])

In [77]:
c.dtype

dtype('<U1')

In [35]:
d = np.array([{'a': 1}, sys])

In [36]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [37]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [38]:
A.shape

(2, 3)

In [39]:
A.ndim

2

In [40]:
A.size

6

In [79]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [42]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [80]:
B.shape

(2, 2, 3)

In [81]:
B.ndim

3

In [82]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [83]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [84]:
C.dtype

dtype('O')

In [85]:
C.shape

(2,)

In [86]:
C.size

2

In [87]:
type(C[0])

list

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [51]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [52]:
A[1]

array([4, 5, 6])

In [53]:
A[1][0]

4

In [ ]:
# A[d1, d2, d3, d4]

In [88]:
A[1, 0]

4

In [89]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [91]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [92]:
A[:2, 2:]

array([[3],
       [6]])

In [93]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
A[1] = np.array([10, 10, 10])

In [95]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [96]:
A[2] = 99

In [97]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [98]:
a = np.array([1, 2, 3, 4])

In [99]:
a.sum()

10

In [100]:
a.mean()

2.5

In [101]:
a.std()

1.118033988749895

In [102]:
a.var()

1.25

In [103]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [104]:
A.sum()

45

In [105]:
A.mean()

5.0

In [106]:
A.std()

2.581988897471611

In [107]:
A.sum(axis=0)

array([12, 15, 18])

In [108]:
A.sum(axis=1)

array([ 6, 15, 24])

In [109]:
A.mean(axis=0)

array([4., 5., 6.])

In [110]:
A.mean(axis=1)

array([2., 5., 8.])

In [111]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [112]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [116]:
a = np.arange(5)

In [117]:
a

array([0, 1, 2, 3, 4])

In [118]:
a + 10

array([10, 11, 12, 13, 14])

In [119]:
a * 10

array([ 0, 10, 20, 30, 40])

In [120]:
a

array([0, 1, 2, 3, 4])

In [121]:
a += 100

In [124]:
a

array([100, 101, 102, 103, 104])

In [125]:
l = [0, 1, 2, 3]

In [126]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [127]:
a = np.arange(4)

In [128]:
a

array([0, 1, 2, 3])

In [129]:
b = np.array([10, 10, 10, 10])

In [130]:
b

array([10, 10, 10, 10])

In [131]:
a + b

array([10, 11, 12, 13])

In [132]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [133]:
a = np.arange(4)

In [135]:
a

array([0, 1, 2, 3])

In [136]:
a[0], a[-1]

(0, 3)

In [138]:
a[[0, -1]]

array([0, 3])

In [139]:
a[[True, False, False, True]]

array([0, 3])

In [140]:
a

array([0, 1, 2, 3])

In [141]:
a >= 2

array([False, False,  True,  True])

In [142]:
a


array([0, 1, 2, 3])

In [143]:
a[a >= 2]

array([2, 3])

In [144]:
a

array([0, 1, 2, 3])

In [145]:
a.mean()

1.5

In [146]:
a[a > a.mean()]

array([2, 3])

In [147]:
a[~(a > a.mean())]

array([0, 1])

In [148]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [149]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [150]:
A = np.random.randint(100, size=(3, 3))

In [154]:
A

array([[84, 35, 38],
       [ 7, 18, 29],
       [ 9, 83, 34]])

In [155]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([84, 38, 18,  9, 34])

In [156]:
A > 30

array([[ True,  True,  True],
       [False, False, False],
       [False,  True,  True]])

In [157]:
A[A > 30]

array([84, 35, 38, 83, 34])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [158]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [159]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [160]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [161]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [163]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [164]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [165]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [166]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [167]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [168]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [169]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [170]:
np.dtype(float).itemsize

8

### Lists are even larger

In [172]:
# A one-element list
sys.getsizeof([1])

80

In [173]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [174]:
l = list(range(100000))

In [175]:
a = np.arange(100000)

In [177]:
%time np.sum(a ** 2)

CPU times: user 1.8 ms, sys: 940 µs, total: 2.74 ms
Wall time: 3.1 ms


333328333350000

In [176]:
%time sum([x ** 2 for x in l])

CPU times: user 27.8 ms, sys: 11.4 ms, total: 39.1 ms
Wall time: 40.8 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random` 

In [178]:
np.random.random(size=2)

array([0.71105425, 0.44795192])

In [179]:
np.random.normal(size=2)

array([ 0.22689648, -0.30338608])

In [180]:
np.random.rand(2, 4)

array([[0.76605883, 0.15896546, 0.2664927 , 0.77168311],
       [0.82143046, 0.91999203, 0.93551086, 0.59491059]])

---
### `arange`

In [181]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [183]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [184]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [185]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [186]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [187]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [188]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [189]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [190]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [191]:
np.zeros((3, 3), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [192]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [193]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [194]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [195]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [196]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [197]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [201]:
np.eye(8, 8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [199]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [202]:
np.eye(8, 5, k=-3)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [203]:
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)